spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tenki
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

app:
  jwt-secret: daf66e01593f61a15b857cf433aae03a005812b31234e149036bcc8dee755dbb
  jwt-expiration-milliseconds: 60480000


api:
  host:
    baseurl: https://api.openweathermap.org/data/2.5/weather
    appid: