spring:
  security:
    user:
      name: User
      password: User
  datasource:
    url: jdbc:h2:mem:tenki_db
    username: sa
    password: password
    driverClassName: org.h2.Driver
    jpa:
      spring.jpa.database-platform: org.hibernate.dialect.H2Dialect